apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.1 #allow non-root users to mount NFS
  nfs:
    server: nfs-service.default.svc.cluster.local
    path: "/mnt/share"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv1
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.1 #allow non-root users to mount NFS
  nfs:
    server: nfs-service.default.svc.cluster.local
    path: "/mnt/share2"
