apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nfs-server
spec:
  selector:
    matchLabels:
      app: nfs-server
  serviceName: nfs-service
  replicas: 2
  template:
    metadata:
      labels:
        app: nfs-server
    spec:
      containers:
      - name: volume-nfs
        image:  gcr.io/google_containers/volume-nfs:latest
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
#          privileged: true
          allowPrivilegeEscalation: false
          runAsUser: 0
#        resources:
#          limits:
#            cpu: 2000m
#            memory: 5120Mi
#          requests:
#            cpu: 256m
#            memory: 256Mi
        volumeMounts:
        - name: nfs-pvc
          mountPath: "/mnt/test"
  volumeClaimTemplates:
  - metadata:
      name: nfs-pvc
    spec:
      accessModes: [ "ReadWriteMany" ]
      storageClassName: ""
      resources:
        requests:
          storage: 1Gi
