apiVersion: v1 
kind: Pod 
metadata: 
   name: pod 
spec: 
  containers: 
    - name: busybox 
      image: busybox 
      command: ['sh', '-c', 'while true; do echo we-down! >> /tmp/success.txt; sleep 5; done']
