apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: filestore-rwx
provisioner: filestore.csi.storage.gke.io
volumeBindingMode: WaitForFirstConsumer # or Immediate
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  type: pd-standard # using HDD for throughput or pd-balanced for ssd for i/o



