apiVersion: v1 
kind: Pod 
metadata: 
   name: pv-pod1
spec: 
  containers: 
    - name: busybox 
      image: busybox 
      command: ['sh', '-c', 'while true; do echo 4 5 6! >> /output/success.txt; sleep 5; done'] 
      volumeMounts: 
      - name: volume
        mountPath: /output 
  volumes: 
    - name: volume
      persistentVolumeClaim: 
#        claimName: fileserver-claim
        claimName: filestorepvc
