apiVersion: v1 
kind: Pod 
metadata: 
   name: app-pod
spec: 
  containers: 
    - name: busybox 
      image: busybox 
      securityContext:
        allowPrivilegeEscalation: false
        runAsUser: 0
          # privileged: true
      command: ['sh', '-c', 'while true; do echo 4 5 6! >> /output/success.txt; sleep 5; done'] 
      volumeMounts: 
      - name: volume
        mountPath: /output 
  volumes: 
    - name: volume
      persistentVolumeClaim: 
        claimName: app-pvc
