apiVersion: v1
kind: Pod
metadata:
  name: somepod
spec:
  containers:
  - name: somepod
    image: nginx:alpine
    ports:
    - containerPort: 80
      protocol: TCP
    volumeMounts:
    - name: productbook
      mountPath: /pbook
  volumes:
  - name: productbook
    persistentVolumeClaim:
      claimName: demopvc #name of the pvc deployed
