apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demopvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "standard"
  resources:
    requests:
      storage: 100Mi
#  persistentVolumeReclaimPolicy: Retain
#  mountPath: "/productbook"
#  volumeID: "vol0001"


  
